FORMAT: 1A
HOST: https://api.ccb.org.br/api/v1

# Svartbrand API

Aqui você encontra os detalhes de como realizar chamadas em HTTP para a API *Svartbrand*;

## Autenticação [/auth]

### api.auth.info [GET /auth]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"

+ Response 200 (application/json)

    + Body

            {
                "user": {
                    "cod_empresa": "0000000000000",
                    "id_pais": "1",
                    "emp_cidade": "Cincinnati",
                    "dsc_uf": "OH",
                    "cep_cep": "10019",
                    "dsc_empresa": "Badass Company",
                    "emp_razao_social": "Badass Company Industry Ltd.",
                    "emp_endereco": "7th Avenue",
                    "emp_endereco_num": "666",
                    "emp_compl_endereco": null,
                    "emp_bairro": "Downtown",
                    "emp_telefone": "+1 (800) 862-46520",
                    "emp_telefone2": null,
                    "emp_fax": null,
                    "emp_e_mail": "john@badass.com",
                    "emp_home_page": null,
                    "emp_tipo_pessoa": "J",
                    "emp_estadual_rg": "000.000.000.000",
                    "emp_livre_comercio": "0",
                    "emp_data_fundacao": null,
                    "emp_usuario_inc": "sa",
                    "emp_usuario_alt": "john"
                }
            }

### api.auth.login  [POST /auth]

+ Request (application/json)
    
    + Body

            {
                "username": "02548157000112",
                "password": "emp@senha123"
            }

+ Response 201 (application/json)

    + Body

            {
                "token": "Bearer <token>"
            }

## Resultados de Ensaios [/resultados]

### api.resultados.index [GET /resultados]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
    + Attributes
        + data_begin: dd/mm/yyyy (string, optional)
        + data_end: dd/mm/yyyy (string, optional)
        + modalidade: 0 (number, optional) - sendo [0] Todos | [1] Convênio | [2] Avulso | [3] Assistência Técnica | [4] Certificação | [5] Pesquisa & Desenvolvimento

    + Body

            {
                "data_begin": "20/05/2017",
                "data_end": "20/05/2017",
                "modalidade": 0
            }

+ Response 200 (application/json)

        [
            {
                "data":[
                    {
                        "registro":"02292/17",
                        "prod_marca":"Elizabeth",
                        "prod_ref":"HD Basalto Noce",
                        "modalidade":"Avulso",
                        "data_saida":"25/02/2017",
                        "pdf":"<PDF File Content>"
                    },{
                        "registro":"02193/17",
                        "prod_marca":"Elizabeth",
                        "prod_ref":"HD Basalto Noce",
                        "modalidade":"Convênio",
                        "data_saida":"20/03/2017",
                        "pdf":"<PDF File Content>"
                    },{
                        "registro":"00390/17",
                        "prod_marca":"Elizabeth",
                        "prod_ref":"HD Basalto Noce",
                        "modalidade":"Avulso",
                        "data_saida":"10/05/2017",
                        "pdf":"<PDF File Content>"
                    }
                ]
            }
        ]

## Solicitações de Ensaios [/solicitacoes]

### api.solicitacoes.index [GET /solicitacoes]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
    + Attributes
        + data_begin: dd/mm/yyyy (string, optional)
        + data_end: dd/mm/yyyy (string, optional)

    + Body

            {
                "data_begin": "20/05/2017",
                "data_end": "20/05/2017"
            }

+ Response 200 (application/json)

        {
            "data":[
                {
                    "id":"0229217",
                    "registro":"02292/17",
                    "prod_marca":"Elizabeth",
                    "prod_ref":"HD Basalto Noce",
                    "modalidade":"Avulso",
                    "data_solicitacao":"25/02/2017",
                    "status":"Em execução",
                    "status_code":3,
                    "pdf":"<PDF File Content>"
                },{
                    "id":"0219317",
                    "registro":"02193/17",
                    "prod_marca":"Elizabeth",
                    "prod_ref":"HD Basalto Noce",
                    "modalidade":"Convênio",
                    "data_solicitacao":"20/03/2017",
                    "status":"Finalizado",
                    "status_code":5,
                    "pdf":"<PDF File Content>"
                },{
                    "id":"0039017",
                    "registro":"00390/17",
                    "prod_marca":"Elizabeth",
                    "prod_ref":"HD Basalto Noce",
                    "modalidade":"Avulso",
                    "data_solicitacao":"10/05/2017",
                    "status":"Aguardando amostras",
                    "status_code":2,
                    "pdf":"<PDF File Content>"
                }
            ]
        }

### api.solicitacoes.show [GET /solicitacoes/{id}]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"

+ Response 200 (application/json)

        {
            "data":{
                "id": "0229217",
                "registro": "02292/17",
                "empresa": {
                    "cnpj": "00.000.000/0001-07",
                    "razaosocial": "ACME Industrias Ltda"
                },
                "amostra": {
                    "id": "43504",
                    "marca": "ACME Inc",
                    "referencia": "HD Translucido das Arábias",
                    "tipo_material": "Prensado",
                    "tipo_acabamento": "Esmaltado"
                },
                "declaracoes": {
                    "solicitante": "Fulano de Tal da Silva",
                    "dim_nominal": "25cm x 25cm",
                    "dim_fabricacao": "250mm x 253mm x 6.5mm",
                    "grp_abs": "BIIb",
                    "res_abr": "2",
                    "tonalidade": "Preto",
                    "bitola": "5",
                    "lote_fab": "2103124",
                    "data_fab": "20/05/2017",
                    "linha_prod": "5",
                    "horario_prod": "5:35"
                },
                "amst_qtd_pcs": "45",
                "modalidade": "Convênio",
                "obs": "",
                "data_solicitacao": "01/02/2017",
                "data_entrada": "20/02/2017",
                "data_abertura": null,
                "data_inicio": null,
                "data_conclusao": null,
                "data_saida": null,
                "status": "Em execução",
                "ensaios":[
                    {
                        "id": "RT_32",
                        "desc": "Determinação da Expansão por Umidade",
                        "norma": "NBR 13.818/97 - Anexo X",
                        "status": "Aguardando execução",
                        "data_conclusao": null
                    },
                    {
                        "id": "RT_26",
                        "desc": "Determinação da Resistencia ao Manchamento",
                        "norma": "NBR 13.818/97 - Anexo Y",
                        "status": "Aguardando execução",
                        "data_conclusao": null
                    },
                    {
                        "id": "RT_28A",
                        "desc": "Determinação da Resistencia ao Ataque Químico",
                        "norma": "NBR 13.818/97 - Anexo Z",
                        "status": "Aguardando execução",
                        "data_conclusao": null
                    }
                ],
                "pdf": "<PDF File Content>"
            }
        }

### api.solicitacoes.store [POST /solicitacoes]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"

    + Body

            {
                "amostra_id": "29217",
                "tipo_material": "1",
                "tipo_acabamento": "3",
                "amst_qtd_pcs": "45",
                "declaracoes": {
                    "solicitante": "Gabriel Piccin",
                    "dim_nom_a": "25",
                    "dim_nom_b": "25",
                    "dim_fab_a": "250",
                    "dim_fab_b": "253",
                    "dim_fab_c": "6.5",
                    "grp_abs": "BIIb",
                    "res_abr": "2",
                    "tonalidade": "Preto",
                    "bitola": "5",
                    "lote_fab": "2103124",
                    "data_fab": "20/05/2017",
                    "linha_prod": "5",
                    "horario_prod": "5:35"
                },
                "obs": "",
                "ensaios": [
                    "RT_32",
                    "RT_26",
                    "RT_28A",
                ]
            }

+ Response 201 (application/json)

    + Headers


    + Body

            {
                "data":{
                    "id": "0229217",
                    "registro": "02292/17",
                    "empresa": {
                        "cnpj": "00.000.000/0001-07",
                        "razaosocial": "ACME Inc Ltda"
                    },
                    "amostra": {
                        "id": "29217",
                        "marca": "Elizabeth",
                        "referencia": "HD Basalto Noce"
                    },
                    "declaracoes": {
                        "solicitante": "Fulano de Tal da Silva"
                    },
                    "modalidade": "Convênio",
                    "obs": "",
                    "data_solicitacao": "01/02/2017",
                    "data_entrada": null,
                    "data_abertura": null,
                    "data_inicio": null,
                    "data_conclusao": null,
                    "data_saida": null,
                    "status": "Em execução",
                    "status_code": 3,
                    "ensaios":[
                        {
                            "id": "RT_32",
                            "desc": "Determinação da Expansão por Umidade",
                            "norma": "NBR 13.818/97 - Anexo X",
                            "status": "Aguardando execução",
                            "data_conclusao": null
                        },
                        {
                            "id": "RT_26",
                            "desc": "Determinação da Resistencia ao Manchamento",
                            "norma": "NBR 13.818/97 - Anexo Y",
                            "status": "Aguardando execução",
                            "data_conclusao": null
                        },
                        {
                            "id": "RT_28A",
                            "desc": "Determinação da Resistencia ao Ataque Químico",
                            "norma": "NBR 13.818/97 - Anexo Z",
                            "status": "Aguardando execução",
                            "data_conclusao": null
                        }
                    ],
                    "pdf": "<PDF File Content>"
                }
            }

## Cadastro de Ensaios [/ensaios]

### api.ensaios.search [GET /ensaios/search]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
+ Response 200 (application/json)

        {
            "data":[
                {
                    "id": "RT_16",
                    "dsc": "Análise Visual do Aspecto Superficial",
                    "procedimento": "NBR 13818/97 - Anexo A"
                },
                {
                    "id": "RT_17",
                    "dsc": "Determinação da Absorção de Água",
                    "procedimento": "NBR 13818/97 - Anexo B"
                },
                {
                    "id": "RT_18",
                    "dsc": "Determinação da Carga de Ruptura e Módulo de Resistência à Flexão",
                    "procedimento": "NBR 13818/97 - Anexo C"
                },
                {
                    "id": "RT_20",
                    "dsc": "Determinação da Resistência à Abrasão Superficial",
                    "procedimento": "NBR 13818/97 - Anexo D"
                },
                {
                    "id": "RT_24",
                    "dsc": "Determinação da Resistência à Abrasão Profunda",
                    "procedimento": "NBR 13818/97 - Anexo E"
                },
                {
                    "id": "RT_25",
                    "dsc": "Determinação da Resistência ao Gretamento",
                    "procedimento": "NBR 13818/97 - Anexo F"
                },
                {
                    "id": "RT_26",
                    "dsc": "Determinação da Resistência ao Manchamento",
                    "procedimento": "NBR 13818/97 - Anexo G"
                },
                {
                    "id": "RT_28A",
                    "dsc": "Determinação da Resistência ao Ataque Químico",
                    "procedimento": "NBR 13818/97 - Anexo H"
                },
                {
                    "id": "RT_32",
                    "dsc": "Determinação da Expansão por Umidade",
                    "procedimento": "NBR 13818/97 - Anexo J"
                },
                {
                    "id": "RT_33",
                    "dsc": "Determinação do Coeficiente de Dilatação Térmica",
                    "procedimento": "NBR 13818/97 - Anexo K"
                },
                {
                    "id": "RT_35",
                    "dsc": "Determinação do Coeficiente de Atrito",
                    "procedimento": "NBR 13818/97 - Anexo N"
                },
                {
                    "id": "RT_37",
                    "dsc": "Determinação da Resistência ao Impacto",
                    "procedimento": "NBR 13818/97 - Anexo Q"
                },
                {
                    "id": "RT_39",
                    "dsc": "Determinação da Retitude Lateral, da Ortogonalidade, da Curvatura, do Empeno e Dimensões",
                    "procedimento": "NBR 13818/97 - Anexo S"
                },
                {
                    "id": "RT_40",
                    "dsc": "Determinação da Dureza MOHS",
                    "procedimento": "NBR 13818/97 - Anexo V"
                },
                {
                    "id": "RT_42",
                    "dsc": "Determinação da Resistência à Mancha D'Agua",
                    "procedimento": "Procedimento Interno"
                }
            ]
        }

## Cadastro de Amostras [/amostras]

### api.amostras.index [GET /amostras]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
+ Response 200 (application/json)

        {
            "data":[
                {
                "id_amostra": 5588,
                "dsc_amostra": "Branco Gelo",
                "marca": "ACME Inc",
                "alert_amostra": 0,
                "obs_amostra": "",
                "grp_abs": {
                    "id": 2,
                    "descricao": "BIIb Q < 90",
                    "formato": "Quadrado",
                    "superficie": "",
                    "acabamento": "",
                    "area": "> 2500 cm²"
                    }
                },
                {
                "id_amostra": 845,
                "dsc_amostra": "Preto carvão",
                "marca": "ACME Inc",
                "alert_amostra": 1,
                "obs_amostra": "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga nesciunt necessitatibus doloribus architecto porro laboriosam consequuntur cumque odio temporibus labore, excepturi dolor, enim ipsum aliquid, ullam quae fugit quis et.",
                "grp_abs": {
                    "id": 2,
                    "descricao": "Porc. Q < 90",
                    "formato": "Quadrado",
                    "superficie": "Esmaltado",
                    "acabamento": "Retificado",
                    "area": "> 2500 cm²"
                    }
                }
            ]
        }
        
### api.amostras.show [GET /amostras/{id}]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
+ Response 200 (application/json)

        {
          "data": [
            {
              "id": "2985",
              "referencia": "Bianco GL",
              "marca": "Elizabeth",
              "grp_abs": {
                "id": "69",
                "descricao": "porc Q > 2500",
                "superficie": "técnico/natural",
                "acabamento": "Não Retificado",
                "formato": "Quadrado",
                "area": "> 2500 cm²"
              }
            }
          ]
        }

### api.amostras.search [GET /amostras/search]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
+ Response 200 (application/json)

        {
            "data":[
                {
                    "id":"29217",
                    "referencia":"HD Piazza Italia",
                    "marca": "Embramaco"
                },{
                    "id":"9517",
                    "referencia":"HD Piazza le Franc",
                    "marca": "Embramaco"
                },{
                    "id":"3577",
                    "referencia":"Porcelanato Polido Bege",
                    "marca": "Esther"
                }
            ]
        }
        
### api.amostras.store [POST /amostras]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"

    + Body

            {
                "dsc_amostra": "Branco Gelo",
                "marca": "ACME Inc",
                "alert_amostra": 0,
                "obs_amostra": "",
                "grp_abs": 2
            }

+ Response 201 (application/json)

    + Headers


    + Body

            {
                "id_amostra": 5588,
                "dsc_amostra": "Branco Gelo",
                "marca": "ACME Inc",
                "alert_amostra": 0,
                "obs_amostra": "",
                "grp_abs": {
                    "id": 2,
                    "dsc": "BIIb Q < 90",
                    "formato": "Quadrado",
                    "superficie": "",
                    "acabamento": ""
                }
            }
        
## Cadastro de Grupos [/absgrupos]

### api.absgrupos.search [GET /absgrupos/search]

+ Request (application/json)
    
    + Headers
            
            Authorization: "Bearer <token>"
    
+ Response 200 (application/json)

        {
            "data":[
                {
                    "id": "69",
                    "descricao": "porc Q > 2500",
                    "superficie": "técnico/natural",
                    "acabamento": "Não Retificado",
                    "formato": "Quadrado",
                    "area": "> 2500 cm²"
                },
                {
                    "id": "69",
                    "descricao": "porc Q > 2500",
                    "superficie": "técnico/natural",
                    "acabamento": "Não Retificado",
                    "formato": "Quadrado",
                    "area": "> 2500 cm²"
                },
                {
                    "id": "69",
                    "descricao": "porc Q > 2500",
                    "superficie": "técnico/natural",
                    "acabamento": "Não Retificado",
                    "formato": "Quadrado",
                    "area": "> 2500 cm²"
                }
            ]
        }